pipeline {
    agent any

    stages {
        stage('Hello1') {
            steps {
                echo 'Hello World'
            }
        }
    }


stages {
        stage('Hello2') {
            steps {
                echo 'Hello World'
            }
        }
    }


    stages {
        stage('Hello3') {
            steps {
                echo 'Hello World'
            }
        }
    }

}
